# Generated by Django 5.0.2 on 2024-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_payment_order_ordered_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women fashion', 'Women fashion'), ('Shoes', 'Shoes'), ('Home appliances', 'Home appliances'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture')], max_length=200, null=True),
        ),
    ]
