# Generated by Django 5.0.2 on 2024-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_order_billing_address_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='index.html/'),
        ),
    ]
