# Generated by Django 5.0.2 on 2024-03-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_payment_products_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
