# Generated by Django 4.2.11 on 2024-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
