# Generated by Django 5.0.2 on 2024-03-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
