# Generated by Django 5.0.2 on 2024-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
