# Generated by Django 5.0.2 on 2024-03-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_cartproduct'),
        ('playground', '0016_product_quantity'),
    ]

    operations = [
    ]
