# Generated by Django 4.2.11 on 2024-03-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_cartproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='Cart_Product',
        ),
    ]
