# Generated by Django 5.0.2 on 2024-03-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_merge_0016_cartproduct_0016_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
