# Generated by Django 5.0.2 on 2024-03-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_delete_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
